### ISSUE TITLE
Wrong sass executable on windows

### ISSUE THREAD

**Issue by Guillaume-Lacombe** [SalomonBrys/gradle-sass#2]
Hi,  I found a problem with the "download" mode.

**Description :**
The problem happens on windows and when you let the gradle-sass plugin download and execute dart-sass

build.gradle :
```

plugins {
	id "com.github.salomonbrys.gradle.sass" version "1.0.1" apply false
}
apply plugin:"com.github.salomonbrys.gradle.sass"
// see issue https://github.com/SalomonBrys/gradle-sass/issues/1 for mor explanations


sass {
	download {
		version = "1.15.2" 
	}
}
```
Running in git bash or in windows command line leads to the same issue :
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sassCompile'.
> A problem occurred starting process 'command 'C:\Users\...\.gradle\sass/1.15.2/dart-sass/sass''
```

This should be : C:\Users\\...\\.gradle\sass/1.15.2/dart-sass/sass.bat
(notice the .bat extension)

**Cause :**
I think the cause lies in the file : src/main/kotlin/com/github/salomonbrys/gradle/sass/SassTask.kt
```
...
 @TaskAction
    internal fun compileSass() {
        val exe = (project.extensions["sass"] as SassExtension).exe

        getSource().visit {
            if (isDirectory || name.startsWith("_"))
                return@visit

            project.exec {
                executable = when (exe) {
                    is SassExtension.Exe.Local -> exe.path
                    is SassExtension.Exe.Download -> "${exe.outputDir.absolutePath}/${exe.version}/dart-sass/sass"
				}
...
```
the sass executable is hardcoded, but  on windows this should be 
`"${exe.outputDir.absolutePath}/${exe.version}/dart-sass/sass.bat"`

This can be fixed by using the attribute SassExtension.DEFAULT_SASS_EXE

here is what I think about : 
```
...
	@TaskAction
	internal fun compileSass() {
		def sassExtension = project.extensions["sass"] 
		def exe = sassExtension.exe

		getSource().visit {
			if (isDirectory || name.startsWith("_"))
				return@visit

			project.exec {
				executable = when (exe) {
					is SassExtension.Exe.Local -> exe.path
					is SassExtension.Exe.Download -> "${exe.outputDir.absolutePath}/${exe.version}/dart-sass/${sassExtension.DEFAULT_SASS_EXE}"
				}
			}
...
```	

**Workaround  :** 
I also found a workaround. I let the plugin download and extract dart-sass and just before the sassCompile task I switch (programmaticaly) the confugration from "download" to "local". In fact the local is just pointing to the freshly downloaded sass directory.

build.gradle :
```
sass {
	download {
		version = "1.15.2" 
	}

	sassCompile {

		doFirst{
			def sassExtension = project.extensions["sass"] 
			def exe = sassExtension.exe
			if( exe instanceof com.github.salomonbrys.gradle.sass.SassExtension.Exe.Download ){
				def executable = "${exe.outputDir.absolutePath}/${exe.version}/dart-sass/${sassExtension.DEFAULT_SASS_EXE}"
				sassExtension.exe = new com.github.salomonbrys.gradle.sass.SassExtension.Exe.Local(executable)
			}
		}
	}
}
```

**Comment by SalomonBrys** [comment]
Thanks a lot for an amazing report !
Maybe you want to propose a pull request, so that you can be listed as a contributor ?
Or I can implement the fix if you'd like, your choice ;)

**Comment by Guillaume-Lacombe** [comment]
Your welcome :)
It will take  time before I can make the pull request.
In fact I am at work right now (France) and I did not take the time to clone the project and setup the environment for developping the fix. (And I am a beginner in Kotlin)

**Comment by SalomonBrys** [comment]
Ça roule, je m'en occupe donc :)
Merci pour ticket super précis !
Ça sera corrigé pour la version 1.0.2.

**Comment by SalomonBrys** [comment]
Version 1.0.2 has been published: https://plugins.gradle.org/plugin/com.github.salomonbrys.gradle.sass

It fixes this issue.
