### ISSUE TITLE
Expose outputStyle property

### ISSUE THREAD

**Issue by cocorossello** [SalomonBrys/gradle-sass#5]
Hi,

Thanks for the plugin, I found it very useful. 

I would like to be able to configure outputStyle property (from dart-sass), so I can compile and compress the css in one go. 

I'm trying to figure out how to do it, I think it's easy but I haven't developed any gradle plugin.

**Comment by cocorossello** [comment]
I managed to get a working PR (thank god it's easy to write a gradle plugin).

https://github.com/SalomonBrys/gradle-sass/pull/6

**Comment by SalomonBrys** [comment]
This has been implemented in 1.2.0 in a type-safe way:

```kotlin
sassCompile {
    style = compressed
}
```
